### ISSUE TITLE
FEATURE - Add docker images new releases widget

### ISSUE THREAD

**Issue by bigsk1** [glanceapp/glance#120]
Would be nice to have something similar to Github releases but for newly released docker images of selected projects. 

Via dockerhub and/or github images. 

The idea is to have a page were I can see all the new images that have been released and be able to update my docker images manually.

 The option to show release notes and tags would be a plus.

**Comment by svilenmarkov** [comment]
Hey, thanks for the idea! 

That would be pretty cool actually, I'll try and get it added in the next release since it fits with the theme I'm going for. 

As for the release notes, I'm not sure where they'd come from since I don't think dockerhub or ghcr have support for them?

**Comment by bigsk1** [comment]
> Hey, thanks for the idea!
> 
> That would be pretty cool actually, I'll try and get it added in the next release since it fits with the theme I'm going for.
> 
> As for the release notes, I'm not sure where they'd come from since I don't think dockerhub or ghcr have support for them?

Ya that's true, if there was a why to see the tag , OS, size, date and the digest was clickable it would take you to the image layer details  like 

https://hub.docker.com/layers/ollama/ollama/latest/images/sha256-79cfa889ba13ccadaa5fcd8681be6270b0fbcd5ff2dd576ca41d0744218e50a0?context=explore

**Comment by svilenmarkov** [comment]
@bigsk1 Sort of limited at the moment but I've added the ability to select from different sources in the releases widget, Docker Hub being one of them:

![releases-widget-preview](https://github.com/user-attachments/assets/21e41634-dddf-4af9-b3a4-a70044315a37)

I think it makes sense to have all releases in one place rather than having a separate widget for just container image releases. Those who prefer to have them separately can still add a second releases widget with just containers.
