### ISSUE TITLE
Alternate lobsters

### ISSUE THREAD

**Issue by bersace** [glanceapp/glance#129]
Hi,

Congratulation for 0.5.0 and thank you very much for Glance.

The new lobsters plugin is awesome and helps participating to discussions right from glance.

[lobsters is open source software](https://github.com/jcs/lobsters) and is used e.g. by https://www.journalduhacker.net/ . Is it possible to use an alternative server for lobster plugin ?

cc @jonasknobloch

Regards,
Étienne

**Comment by jonasknobloch** [comment]
As of right now the Lobsters URL is [hardcoded](https://github.com/glanceapp/glance/blob/b83bf9bc096dc2117266d770aeb4b90e72f308e8/internal/feed/lobsters.go#L68). AFAIK there are no fixed API specs, but as long as every instance is running a compatible version, allowing to override the baseURL should be enough.

**Comment by svilenmarkov** [comment]
Hey,

This was an oversight on my part as I assumed that there's just a single instance of the site. @jonasknobloch did originally implement the widget in a way that would allow specifying the full URL but I changed it to what it is now since I didn't want the user to have to figure out the endpoints for sorting and the tags. I'll add a property that would allow changing the base URL in the next release.

Thanks for bringing this up.

**Comment by jonasknobloch** [comment]
Another reason for why this might be helpful is custom filters. Registered lobsters users can view their custom filtered feed by appendig a special token via a query parameter.

**Comment by Angelmmiguel** [comment]
Hey @svilenmarkov @jonasknobloch,

I loved this project and would like to start contributing some code. Are you open for contributions on this issue? I'm happy to work on this. I see there are different topics on this discussion, like custom filters and different base URLs. I can start with the base URL and create later on a separate PR for other features.

Thanks!

**Comment by svilenmarkov** [comment]
Hey @Angelmmiguel, thanks for offering help! 

This should be an easy implementation and you're free to contribute if you like, though admittedly I am slow with going through PRs.
