### ISSUE TITLE
Feature Request: Multi-client ability

### ISSUE THREAD

**Issue by Wallenstein2010** [glanceapp/glance#139]
Hello,
Have you perhaps already considered adding a multi-client option? 
I have been looking for a dashboard solution for my team for a long time. Ideally 
with a profile that the individual user can then customise.
Is there such a thing at all?

**Comment by svilenmarkov** [comment]
Hey, thanks for the suggestion!

Unfortunately there's no plans to add support for multiple users, at least for the foreseeable future. There's a bunch of reasons for that, though primarily because doing it properly would require a good amount of work which I'd rather dedicate towards adding other features. 

That's not to say you couldn't achieve most of what you want. You _could_ spin up multiple instances of Glance for every user (Glance is fairly lightweight, only using ~25mb of RAM based on my observations) and put them behind something like Authentik or Authelia. It's an involved process but definitely would work.
