### ISSUE TITLE
[Bug(?)] Version tag not showing correctly in frontend

### ISSUE THREAD

**Issue by jbonadiman** [glanceapp/glance#202]
Hi 👋!
I noticed that in the release widget, if a repository has a tag in the format `1.23.4` or `v12.34` (just numbers or prefixed with a lowercase v), the version is labelled correctly in glance's frontend with a `v` (lowercase v) prefix. But if the tag starts with a uppercase V, than the frontend shows the v doubled. I noticed this with this example:
https://github.com/crocodilestick/Calibre-Web-Automated/releases/tag/V2.0.1
The frontend shows to me `vV2.0.1`, instead of the `v2.0.1` I'd expect.
I labelled this as a possible bug, because it's not really serious and I'm not sure it's desirable to fix that in glance.

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting this! 

That is indeed a bug. To keep things consistent I prepend `v` to the version if it doesn't start with it but forgot to account for when it's present and capitalized. I never noticed this issue because none of the repositories I've added to my instance have so far tagged their versions with a capital `V`. I'll have this fixed for the next release.
