### ISSUE TITLE
[Bug] Bookmark columns are mis-aligned with group title

### ISSUE THREAD

**Issue by cody-at-ats** [glanceapp/glance#217]
Hi, thank you for creating an awesome dashboard.

Everything is working great, but I noticed a minor issue when a bookmark list gets a bit long, then the title of the group is offset from the list like in this screenshot:

![image](https://github.com/user-attachments/assets/89d9546e-fe9d-4b51-9271-a977a3f517ef)

I'm not sure if this was changed or existed in a previously release. Happy to try some things out or maybe customize some css if needed.

_Note: the issue does not occur if the screen width is small enough that the bookmarks are displayed in a single column._

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting this!

I could not replicate the issue, could you please double check if you've accidentally defined 4 groups rather than 3 where the first group has only a title and no links in it? If that's not the case, could you post just the bookmarks widget configuration you used? You can of course redact links/titles/icons. 

Side note: while trying to replicate this I did find a different bug where the icons of the links were unintentionally shrinking, I'll get that fixed with the next release.

**Comment by cody-at-ats** [comment]
Sure! I don't believe there's 4 groups with only a title but my eyes may be deceiving me :/

That's good news that this enabled you to fix another bug :)

Here is the bookmarks widget config I have with everything redacted (it's yml but GH only allows .txt :()

[bookmarks.txt](https://github.com/user-attachments/files/16985659/bookmarks.txt)

**Comment by svilenmarkov** [comment]
It does look like that's what happened, YAML is the devil sometimes. 😅 

Notice the extra `-` in front of `links`:

```diff
  - type: bookmarks
    groups:
      - title: Redacted Title Here
--    - links:
++      links:
          - title: Redacted Title Here
            url: https://redacted.com
            icon: redacted-logo.png
            same-tab: true
```

**Comment by cody-at-ats** [comment]
Wow. Thank you. Must be tired today :(. Definitely no issue here other than my 👀.

**Comment by cody-at-ats** [comment]
Wow. Thank you. Must be tired today :(. Definitely no issue here other than my 👀.
