### ISSUE TITLE
Bug: cannot unmarshal !!seq into glance.Config

### ISSUE THREAD

**Issue by LazyStability** [glanceapp/glance#272]
Hello, I wanted to try out the project but can't seem to get it running. I tried on NixOs and Fedora workstation and got the same error.

### nix
1. git clone https://github.com/glanceapp/glance.git 
2. cd glance
3. nix-shell -p go
4. Copy and paste [the first example](https://github.com/glanceapp/glance/blob/main/docs/preconfigured-pages.md) into glance.yml
5. go run . 

### Fedora
1. git clone https://github.com/glanceapp/glance.git
2. sudo dnf install go
3. cd glance
4. Copy and paste [the first example](https://github.com/glanceapp/glance/blob/main/docs/preconfigured-pages.md) into glance.yml
5. go run . 

Got the same error both times:
```
failed parsing config file: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into glance.Config
exit status 1
```
go version is
go version go1.23.3 linux/amd64 - nix
go version go1.22.9 linux/amd64 - fedora

**Comment by svilenmarkov** [comment]
Hey, the example pages need to be placed under a top level `pages:` key, you can read more about that [here](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#pages). I decided not to include it in the preconfigured page configs because if someone wanted to copy-paste multiple pages they'd have to remove the first line for each. 

I'll add a note to the document about that, sorry for the confusion.

**Comment by LazyStability** [comment]
Ah didn't read that as I wanted to try the project first, before diving into the configuration option. The missing yml key should have clued me in. Thank you very much for your help, much appreciated.
